Neos:
  Neos:
    nodeTypes:
      groups:
        newsletter:
          position: 'start'
          label: 'DirectMail Newsletter'
    fusion:
      autoInclude:
        DirectMail.Newsletter: true
    userInterface:
      translation:
        autoInclude:
          DirectMail.Newsletter:
            - Main
            - Modules
            - 'NodeTypes/*'
      inspector:
        dataTypes:
          'Neos\Media\Domain\Model\ImageInterface':
            editorOptions:
              features:
                resize: TRUE
    modules:
      directMailNewsletter:
        label: 'DirectMail Newsletter'
        controller: '\Neos\Neos\Controller\Module\ManagementController'
        description: 'DirectMail Newsletter'
        icon: 'icon-envelope'
        resource: 'Neos_Neos_Backend_Module_Management'
        submodules:
          Recipients:
            label: DirectMail.Newsletter:Modules:recipients.label
            controller: '\DirectMail\Newsletter\Controller\RecipientController'
            description: DirectMail.Newsletter:Modules:recipients.description
            icon: 'icon-user'
            actions:
              index:
                label: DirectMail.Newsletter:Modules:recipients.buttonlabel
                title: DirectMail.Newsletter:Modules:recipients.buttonlabel
          Categories:
            label: DirectMail.Newsletter:Modules:categories.label
            controller: '\DirectMail\Newsletter\Controller\CategoryController'
            description: DirectMail.Newsletter:Modules:categories.description
            icon: 'icon-th-list'
            actions:
              index:
                label: DirectMail.Newsletter:Modules:categories.buttonlabel
                title: DirectMail.Newsletter:Modules:categories.buttonlabel
          Send:
            label: DirectMail.Newsletter:Modules:send.label
            controller: '\DirectMail\Newsletter\Controller\SendController'
            description: DirectMail.Newsletter:Modules:send.description
            icon: 'icon-mail-forward'
            actions:
              index:
                label: DirectMail.Newsletter:Modules:send.buttonlabel
                title: DirectMail.Newsletter:Modules:send.buttonlabel
          Queue:
            label: DirectMail.Newsletter:Modules:queue.label
            controller: '\DirectMail\Newsletter\Controller\QueueController'
            description: DirectMail.Newsletter:Modules:queue.description
            icon: 'icon-time'
            actions:
              index:
                label: DirectMail.Newsletter:Modules:queue.buttonlabel
                title: DirectMail.Newsletter:Modules:queue.buttonlabel
  Flow:
    i18n:
      defaultLocale: de
DirectMail:
  Newsletter:
    adminName: 'Admin Name'
    adminMail: 'postmaster@domain.com'
    replyToMail: 'reply@domain.com'
    replyToName: 'Reply Name'
    subscribeSubject: 'Newsletter Anmeldung'
    subscribeBody: '<h2>Vielen Dank für Ihr Interesse!</h2> <p>Es freut uns sehr, dass Sie sich für den Erhalt unseres Newsletter registriert haben.</p> <p>Falls Sie sich nicht oder irrtümlich registriert haben, können Sie Ihre Registrierung mit Klick auf den folgenden Link widerrufen.</p>'
    subscribeFooter: '<p>Beste Grüße<br />Ihr Newsletter Team</p>'
    unsubscribeButtonText: 'Registrierung widerrufen!'
    unsubscribeLink: 'http://neos3dev.patriceckhart.com/unsubscribe.html'
    senderName: 'Mail Name'
    senderMail: 'newsletter@domain.com'
    salutation1: 'Mister'
    salutation2: 'Miss'
    salutation3: 'Family'
    presalutation1: 'Dear'
    presalutation2: 'Dear'
    presalutation3: 'Dear'
    newsletterSite: 'newsletter'